# Generated by Django 5.1.3 on 2025-01-21 14:45

import apps.courses.models
import apps.courses.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_date',), 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ('section_number',), 'verbose_name': 'Sección del curso', 'verbose_name_plural': 'Secciones del curso'},
        ),
        migrations.AlterModelOptions(
            name='courseslibrary',
            options={'verbose_name': 'Biblioteca de cursos marcados', 'verbose_name_plural': 'Bibliotecas de cursos marcados'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('episode_number',), 'verbose_name': 'Episodio', 'verbose_name_plural': 'Episodios'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_date',), 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='requisite',
            options={'verbose_name': 'Requisito', 'verbose_name_plural': 'Requisitos'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'ordering': ('-date',), 'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterModelOptions(
            name='whatlearnt',
            options={'verbose_name': 'Aprendizaje', 'verbose_name_plural': 'Aprendizajes'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID de la respuesta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_accepted_answer',
            field=models.BooleanField(default=False, verbose_name='Es respuesta aceptada'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Votos'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='Más vendido'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.ManyToManyField(blank=True, to='courses.comment', verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='course',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=18, null=True, verbose_name='Precio comparativo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.CharField(default=0, max_length=20, verbose_name='Duración del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.ManyToManyField(blank=True, to='courses.coursesection', verbose_name='Secciones del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('espanol', 'Espanol'), ('english', 'English')], max_length=50, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='course',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=100, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(blank=True, to='courses.question', verbose_name='Preguntas'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.ManyToManyField(blank=True, to='courses.rate', verbose_name='Calificaciones'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requisite',
            field=models.ManyToManyField(blank=True, to='courses.requisite', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.resource', verbose_name='Recursos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sales_video',
            field=models.FileField(upload_to=apps.courses.models.course_directory_path, verbose_name='Video promocional'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sold',
            field=models.IntegerField(blank=True, default=0, verbose_name='Vendidos'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_rating',
            field=models.IntegerField(default=0, verbose_name='Calificación de estudiantes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.courses.models.course_directory_path, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_learnt',
            field=models.ManyToManyField(blank=True, to='courses.whatlearnt', verbose_name='Qué aprenderás'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='courses.episode', verbose_name='Episodios'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='section_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de sección'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='section_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID de la sección'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='courseslibrary',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='courseslibrary',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de episodio'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID del episodio'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to=apps.courses.models.course_directory_path, validators=[apps.courses.validators.validate_is_video], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='questions',
            field=models.ManyToManyField(blank=True, to='courses.question', verbose_name='Preguntas'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.resource', verbose_name='Recursos'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_accepted_answer',
            field=models.BooleanField(default=False, verbose_name='Tiene respuesta aceptada'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID de la pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='question',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Número de calificación'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.courses.models.course_directory_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='Cursos relacionados'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID del sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sub_title',
            field=models.CharField(max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.courses.models.sector_directory_path, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='courses.answer', verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.CharField(choices=[('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1, verbose_name='Voto'),
        ),
        migrations.AlterField(
            model_name='whatlearnt',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='whatlearnt',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
    ]
