# Generated by Django 5.1.3 on 2025-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Precio comparativo'),
        ),
    ]
